### ISSUE TITLE
Output images not opening

### ISSUE THREAD

**Issue by vparxX** [makevoid/opensea-images-downloader#1]
Hi, 

I managed to make it work using Ruby and Bundler and the images get uploaded to the Output folder.

However, the .PNGs are coming corrupted, they don't open in any image viewer and when trying to open in Photoshop it says:
"PNG file corrupted by ASCII conversion"

Any ideas how I could get the data correctly?

Ps.: I'm not a developer so maybe I'm doing something wrong.

Thank you!

**Comment by makevoid** [comment]
which collection? maybe I can try to reproduce

**Comment by vparxX** [comment]
I wanted to get the Mekaverse collection: https://opensea.io/collection/mekaverse

But I also tried with several collections and the results were the same. The images gets uploaded to the output folder but corrupted or not possible to open.

**Comment by makevoid** [comment]
Hi @vparxX , you were right, I installed a fresh windows VM and was able to reproduce your issue. 

Your issue is fixed now, please pull / download the latest version of this repo and run it, you should be able to see the images!

Thanks for reporting it as an issue!
