### ISSUE TITLE
Images being retrieved in wrong order and labelled incorrectly

### ISSUE THREAD

**Issue by NoPawsing** [makevoid/opensea-images-downloader#2]
Hello! I was downloading the Lazy Lions NFT collection and had no issues up until Lion #500. After that the next image downloaded was actually #520 but labelled as 501, and every image downloaded after that was misaligned by a seemingly random amount  (#2798 was labelled 2799, #2800 was labelled 2796 somehow?, etc.) didn't modify the code at all, no idea what the cause could be.

**Comment by makevoid** [comment]
hi, thanks for filing this issue

unfortunately the file names (the ones you called labels) are not corresponding to the NFT issue number, they're just the number of the downloaded file

if the downloader for some reason receives a connection error it just skips that file

I could add a retry feature to the deployer but at the moment this is not supported and it will just skip the image

**Comment by NoPawsing** [comment]
ah, I see. thank you for the response!
