### ISSUE TITLE
Rake aborting with error

### ISSUE THREAD

**Issue by NoPawsing** [makevoid/opensea-images-downloader#4]
Hello again! I have been recieving an error that aborts the rake. Here it is in a pastebin.

https://pastebin.com/7E7dvcKe

Not sure if this is a local problem or an api issue.

**Comment by makevoid** [comment]
Hi, thanks for reporting, can I ask which collection?

**Comment by makevoid** [comment]
I should have fixed this error with the latest code push, please redownload/update the library and try to run it again

thanks for opening the issue, please comment again if you have the same problem
